### ISSUE TITLE
[bug] auction house search listing is incomplete

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/minimanager#43]
go 2nd or consecutive pages, you will find empty listing.

**Comment by Aokromes** [comment]
maybe those commits can fix them
https://github.com/krtechnics/minimanager/commits/master

**Comment by jackpoz** [comment]
this is because the ahbot auctions with itemowner 0 are filtered out by the sql query

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/minimanager/commit/96ca6a9f7b8c52788c2aacaf973d3ec6bf7f4278
