### ISSUE TITLE
No Login after Trinitycore kick sha out

### ISSUE THREAD

**Issue by tails2k** [TrinityCore/minimanager#51]
Cant Login to the Website after Trinitycore kick out the SHA Pass.

Its a new one now and it would be nice when you can fix it :) 

"Core/Authserver: Removal of sha_pass_hash, compatibility fields, and ……everything that uses them"

**Comment by Aokromes** [comment]
works for me (TM)

**Comment by tails2k** [comment]
sorry!!! checkout the new version and works! please close
