### ISSUE TITLE
Unable to login or create new account

### ISSUE THREAD

**Issue by TQPS** [TrinityCore/minimanager#52]
Unable to login or create new accounts since recent update.

In 288669f2b0caf7a22fc738da356af327c65d77f9 some new SQL updates were added.

`SQL/update/2020_08_11_mmfpm_changes.sql` - I applied it to database.

When I try to log in now I get stuck on the following:

![image](https://user-images.githubusercontent.com/66294837/93411055-a3ee8480-f8dd-11ea-9c0e-c1e44da75f0e.png)

I assume when I ran the update it of course deleted my `mm_account` table so cant login.

So now I try to create a new one. Cant create same one as before because it says "already exists". Creating a new one gets stuck on (After accepting Terms of service):

![image](https://user-images.githubusercontent.com/66294837/93411338-49095d00-f8de-11ea-9abf-335420971e2d.png)

Otherwise the site appears normal and updates up time, players, etc fine - just cant login or create account.

I've uninstalled and reinstalled a couple of times but it hasn't changed anything.

Anyone else experienced this?

**Comment by Aokromes** [comment]
login works for me, ofc updated minimanager must be used with updated trinitycore revisions.

**Comment by TQPS** [comment]
I definitely keep the core up to date:

![image](https://user-images.githubusercontent.com/66294837/94740432-fcca1c80-03b5-11eb-94a6-91c0f7818ca9.png)

The manager appears to work fine - reads DB and displays everything in the right place. It's only been since recent login changes.

![image](https://user-images.githubusercontent.com/66294837/94740633-57637880-03b6-11eb-91bb-6b5dea0f97bb.png)

I typically don't like to play with anything that works but Is there a way to get an account in manually?

**Comment by jackpoz** [comment]
did you enable gmp library in your PHP ?

**Comment by TQPS** [comment]
Just saw the latest commit page and applied all the updates.

Read the "How to" - enabled gmp as suggested and restarted Apache.

I'm logged in with an account from the Auth DB I believe as mm_account is still empty.

Appreciate the updates. It's working again now.

Many thanks for the continued efforts.

**Comment by jackpoz** [comment]
I set it up 2 days ago and I had the same issue as yours, I debugged and saw gmp was missing.

Glad it helped :)
