### ISSUE TITLE
quest tracker broken on php 7.4

### ISSUE THREAD

**Issue by Aokromes** [TrinityCore/minimanager#62]
https://gist.github.com/Aokromes/f5f8d1cc028d03dc7b97d993d737b53b

**Comment by Faq** [comment]
Any repo steps?

**Comment by Aokromes** [comment]
go to any character to find the quests he got :)

**Comment by Aokromes** [comment]
@leelf00  any idea on this?

**Comment by leelf00** [comment]
I made a PR,need test it with php below 7.2.
