### ISSUE TITLE
Laravel Todo

### ISSUE THREAD

**Issue by flashadvocate** [TrinityCore/minimanager#84]
Slew of things to do here, so going to start with a naive list of the files in classic MM since they are separated out by their functionality. We can clean it up later as things get done.

Ordered alphabetically and not by priority.

### Basic functionality
- [ ] ahstats
- [ ] backup
- [ ] char_achieve
- [ ] char_edit
- [ ] char_extra
- [ ] char_list
- [ ] char_mail
- [ ] char_pets
- [ ] char_rep
- [ ] char_spell
- [ ] char_talent
- [ ] command
- [ ] creature
- [ ] edit
- [ ] error
- [ ] events
- [ ] game_object
- [ ] guildbank
- [ ] honor
- [ ] index - landing page / quick view stats
- [ ] instances
- [ ] IP2Location??
- [ ] IRC ? Discord ?
- [ ] mail_on
- [ ] map
- [ ] message
- [ ] motd
- [ ] register
- [ ] run_patch
- [ ] spelld
- [ ] tele
- [ ] ticket
- [ ] user

#### Bonus functionality
- [ ] Themes - Malachite
- [ ] Themes - RGB
- [ ] Themes - Sulfure
- [ ] Themes - Universe

### Language translations
- [ ] english
- [ ] german

#### Bonus translations... need volunteers later
- [ ] outdated/croatian
- [ ] outdated/czech
- [ ] outdated/french
- [ ] outdated/italian
- [ ] outdated/mandarin
- [ ] outdated/norwegian
- [ ] outdated/persian
- [ ] outdated/portuguese
- [ ] outdated/russian
- [ ] outdated/spanish
- [ ] outdated/turkish

**Comment by Faq** [comment]
lol why? what changed?

**Comment by flashadvocate** [comment]
> lol why? what changed?

KingPin asked me to move the refactor to a different repo :)

https://github.com/TrinityCore/TC-Manager/tree/develop

Plus, this is a pretty significant move, and in a lot of ways will have very little connection to the original project, so probably makes sense to diverge now and not confuse people.

**Comment by Faq** [comment]
shouldnt in that projects readme be something that it is based of this project (or credit about idea) and full rewrite in Laravel framework?

**Comment by flashadvocate** [comment]
> shouldnt in that projects readme be something that it is based of this project (or credit about idea) and full rewrite in Laravel framework?

Absolutely. Though, my cursory perusing did not reveal the original author (before amit) so I don't know exactly who to include outside of the folks on the contributor list. Nevertheless, credit will be given where due :)
