### ISSUE TITLE
no mmftc database

### ISSUE THREAD

**Issue by zichie** [TrinityCore/minimanager#9]
I have no mmftc database,how can i donwload?
I use a trinitycore someone compileed ，I can't compile the service! so there was no database for minimanager, who can tell me where is it,where can download?

**Comment by jackpoz** [comment]
don't use a repack, compile trinitycore yourself

**Comment by Aokromes** [comment]
very likely you mean
https://raw.githubusercontent.com/TrinityCore/minimanager/master/SQL/mmfpm.sql
